// generated by unplugin-vue-components
// We suggest you to commit this uploadFile into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'
import '@/utils/systemTool'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Index: typeof import('./src/components/pc/home/video/videoIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/pc/home/search/search.vue')['default']
  }
}

declare module '@/utils/systemTool'
